fix: visibility of icons in input
scaffold-eth/scaffold-eth-2 pull request #320
Opened 2023-04-24 10:35 UTC by kevinjoshi46b

Solves #319

The input icons now look like this:

`*` here:
![image](https://user-images.githubusercontent.com/62877695/233971864-57b372d9-fd03-41d4-97f4-cb40cfcccacf.png)
![image](https://user-images.githubusercontent.com/62877695/233971907-c469dea2-401a-4d2a-9204-ba61ce238827.png)

`$, Ξ` here:
![image](https://user-images.githubusercontent.com/62877695/233972025-9fb86e59-6347-4510-bfbf-e3ed47903a1a.png)
![image](https://user-images.githubusercontent.com/62877695/233971968-fb45d17c-2faa-4079-b2c3-e773c2588f68.png)

and similar for `#` in byte input

2023-04-24 19:14 UTC, damianmarti approved these changes
LGTM!

2023-04-25 07:43 UTC, carletex requested changes
@kevinjoshi46b  The idea of having daisy themes is to use those colors (primary, secondary, accent, neutral, etc) so they always look consistent if you change your theme colors in `tailwind.config.js`.

If we hardcode a color, like `text-gray-400`, you are "disconnecting" it from the theme.

From DaisyUI:
![image](https://user-images.githubusercontent.com/2486142/234207453-c19cc5f2-d3cc-40cf-ba81-4faccf4154b2.png).

So we need to use a color from the theme (maybe we need to re-think colors in there)

Also, for me, it's not that bad how they look currently:

![image](https://user-images.githubusercontent.com/2486142/234208340-96620e8f-11b8-4fb0-8141-0a9dd773d318.png)

cc @damianmarti @technophile-04

2023-04-25 13:42 UTC, kevinjoshi46b commented
> If we hardcode a color, like `text-gray-400`, you are "disconnecting" it from the theme.

Alright ya this is a good point.

> Also, for me, it's not that bad how they look currently:
> 
> ![image](https://user-images.githubusercontent.com/2486142/234208340-96620e8f-11b8-4fb0-8141-0a9dd773d318.png)

Maybe the `*` is fine because its a more dense icon (but it would probably still go unnoticed maybe on a bigger screen) what about `Ξ` ?

> So we need to use a color from the theme (maybe we need to re-think colors in there)

Ya I do feel this might be needed since the colors are too close and not too contradicting.

Would like to know others opinions too.

2023-04-25 16:27 UTC, technophile-04 commented
> Maybe the * is fine because its a more dense icon (but it would probably still go unnoticed maybe on a bigger screen)

I feel they are visible in `main` branch, like I have a kind of big monitor screen and looks great their too...we also had improved their asociality before check #170 

![Screenshot 2023-04-25 at 9 41 22 PM](https://user-images.githubusercontent.com/80153681/234340372-4ad9c41c-9e02-4472-af18-caf3ceadee30.jpg)

> what about Ξ ?

Yeah, as Carlos mentioned nice catch it can be improved and should have been `text-accent`....lol `text-neutral` a bit too contrasty and kind off misses the theme so I would go with `text-accent` but its just my personal preference 😂

2023-04-25 17:31 UTC, kevinjoshi46b commented
> I feel they are visible in `main` branch, like I have a kind of big monitor screen and looks great their too...

That's great not an issue there then

> `text-neutral` a bit too contrasty

Ohhh yes, its brighter then the input number itself :)

I majorly noticed this issue in `Ξ` and then just ended up changing the rest as well assuming they have a similar issue but ya it seems like just changing from `text-accent` -> `text-primary` is good enough.

2023-04-25 18:17 UTC, carletex commented
@kevinjoshi46b You did it the other way around.

You changed "text-accent" to "text-primary" in integer & bytes inputs, and left the Ξ as it was. Now I can barely see them.

primary:
![image](https://user-images.githubusercontent.com/2486142/234365949-d72288a6-1f30-4d8b-936f-95ccc17ab90a.png)

accent:
![image](https://user-images.githubusercontent.com/2486142/234365998-971952ec-4a17-46af-b238-fd5a90c059cb.png)

It's the other way around. You just need to change the  Ξ color inside the EtherInput to "text-accent"

2023-04-25 18:20 UTC, technophile-04 commented
>  from text-accent -> text-primary is good enough

I think it should be `text-primaryt` -> `text-accent` right 😅

Like We keep `IntegerInput` and `BytesInput` as it is because they look good in current `main` as discussed above and just change `EtherInput` from from `text-primary` -> `text-accent` 🙌

2023-04-25 18:44 UTC, kevinjoshi46b commented
> You changed "text-accent" to "text-primary" in integer & bytes inputs, and left the Ξ as it was. Now I can barely see them.

Oops, my bad sorry for the inconvenience

2023-04-26 11:27 UTC, carletex approved these changes

2023-04-26 11:28 UTC, merged