Add shell script for prod deployments + modify Makefile accordingly
scaffold-eth/scaffold-eth-2 pull request #972
Opened 2024-10-24 08:22 UTC by portdeveloper

Hello! 

## This PR:
-> adds a shell script to give the user a menu for selecting a keystore when deploying to any network other than the local anvil node
-> modifies the makefile to pass in the RPC_URL from the foundry.toml file to the shell script
-> works in linux and macos, since foundry does not work on windows natively, windows is ignored. So we should test this on: linux + wsl + macos
-> removes the need to modify the .env file when changing keystores to use

## Possible To-Do:
-> ‘—keystore’ flag (thx to Shiv for the suggestion) I have some working code on this, but it accepts variables like this:
`yarn deploy --network sepolia my-keystore` 
instead of 
`yarn deploy --network sepolia --keystore my-keystore`
We can also introduce a new script as I couldn't find how to achieve this without doing so.

2024-12-16 10:26 UTC, technophile-04 commented
Hey port thanks for this!! Can you please resolve the merge conflicts we did some tweaks in #1011 🙌

2024-12-17 04:20 UTC, portdeveloper commented
Hey ofc! Will work on this today!

2024-12-18 07:40 UTC, portdeveloper commented
Will do some more testing + UX improvements and ask for your review!

2024-12-23 19:15 UTC, portdeveloper commented
Alright now we get:
-> a direct deployment to the local chain when we run `yarn deploy`
-> a menu in the console when we do a `yarn deploy --network sepolia`
![image](https://github.com/user-attachments/assets/ee39edb0-01fb-426b-9dc4-87a5008311bb)
-> a direct deployment to the specified chain with the specified keystore when we do a `yarn deploy --network sepolia --keystore zort`
![image](https://github.com/user-attachments/assets/629cf89b-2069-4ff7-a654-a5ecf5d6cc49)


https://github.com/user-attachments/assets/653f9df5-b73a-48be-9ec6-db74e79fe143



Also the `deploy-verify` target in the Makefile is unreachable I think 🤔

2025-02-15 08:46 UTC, technophile-04 commented
This is great @portdeveloper been testing it for a while and looks great!! 

Some questions / improvements: 

1. Shall we use `.js` script instead of shell script? So that it's easy for management and don't add extra `scripts` dir for shell script, and maybe import that function in `parseArgs.js` file directly instead of calling `spawnSync` ? 

2. Here can we make more clear maybe something like : `y/n or c to check balance again` 
    
    ![Screenshot 2025-02-15 at 1 19 44 PM](https://github.com/user-attachments/assets/bbe19bca-4a7f-4c44-a9ad-8e77e1f3c345)

3. The check balance step is good but yeah we need to write the password two times while deploying it. If some person have long password which might be common to have...it might be PITA to enter it two times. 

^ Maybe to avoid after user selecting keystore we ask a question wheather he want's to check balance or not, if not we directly deploy (only 1 time password enter) if he wishes to check balance then enter the password twice. 

4. I think we should update the `.env.example` https://github.com/scaffold-eth/scaffold-eth-2/blob/d73d3ebf313864c36aef69bde87203cf0a9a7c57/packages/foundry/.env.example#L18 mentioning that this is only used while local development and can use any keystore name if they want.

2025-02-17 07:22 UTC, portdeveloper commented
Thanks for the review @technophile-04 ! I think your points make great sense! Let me see if I can do a js file!

2025-02-25 18:12 UTC, portdeveloper commented
Alright so now we can:

- [ ] Deploy to localhost normally
- [ ] Deploy to any chain by using --network chainname, it let's you select a keystore 

Things we cannot do:
- [ ]  --keystore flag does not work. Enabling the user to type in stuff to the terminal is definitely harder than it is with a shell script.

2025-02-27 16:04 UTC, technophile-04 commented
Tysm Port! Played around with it, and looks nice! just some comments: 

1. I think we need to update `yarn account` behaviour too in similar way because currently it looks at `.env` but we could keep the flow similar to this where we prompt the list of keystore to check balance for (without the 0th option) 
2. Lets update the `yarn account:import` to also ask for keystore name instead of defaulting it to `scaffold-eth-custom`. 

####  Bug: 

Even though I have `.env#ETH_KEYSTORE_ACCOUNT=scaffold-eth-custom` on localhost it's always using `scaffold-eth-default` I think we need to allow people to use keystore also during localhost development if they want to test. 

---

> `--keystore` flag does not work. Enabling the user to type in stuff to the terminal is definitely harder than it is with a shell script.

> However, we can ask the user to pass in `--keystore` keystorename `--password passwordhere` instead

Yeah the CLI just freezes if I pass `--keystore`. Lets remove that flag for now. We don't want user to enter the password in plain text directly probably. We could take the same path as hardhat where we require user to ender password in masked format. But yeah let's tackle `--keystore` flag in different PR.

2025-02-28 18:08 UTC, portdeveloper commented
I have turned on the dolphin mode. Since I can't make it accept passwords with js, now we dive into js and resurface to makefile multiple times

2025-03-02 06:47 UTC, portdeveloper commented
I have identified the EVIL LINE.
Just importing that selectKeystore file (not even using it btw!) breaks the password input:
Here is the little problem kid, captured in LIVE FOOTAGE!!!
https://screen.studio/share/oOHVh5CO

2025-03-02 16:52 UTC, portdeveloper commented
Below is a quick overview of the current state of this PR:

We use an .env var named LOCALHOST_KEYSTORE_ACCOUNT to have a default keystore.

Commands and what they do:
### deploy related commands
`yarn deploy` -> Uses LOCALHOST_KEYSTORE_ACCOUNT from .env file and deploys to anvil
`yarn deploy --keystore hello` -> Uses hello keystore and deploys to anvil
`yarn deploy --network sepoila` -> Lets the user select a keystore interactively and deploys to sepolia OR create a new keystore
`yarn deploy --network sepolia --keystore i-love-se2` -> Uses i-love-se2 keystore and deploys to sepolia, skipping interactive keystore selection 
``

### other commands
`yarn account` -> Lets the user select a keystore interactively to display balances for it on all chains that we have in foundry.toml(much like the previous implementation, but with interactive selection of any keystore the user has)
`yarn account:import` -> Asks the user for a name and then a private key, uses those values to create a new keystore

2025-03-03 06:22 UTC, technophile-04 commented on packages/foundry/Makefile
> +	@node scripts-js/ListAccount.js $(RPC_URL)
We can remove this now? Since in package.json we are directly calling `checkAccountBalnce.js`? Or maybe lets update this to do 

```
account: 
  @node scripts-js/checkAccountBalnce.js $(RPC_URL)
```

2025-03-03 06:34 UTC, technophile-04 requested changes
> Just importing that selectKeystore file (not even using it btw!) breaks the password input:

Wohhhhh nice catch, thanks for the research and explanation 🙏 

--- 

TYSM Port this is looking almost solid, just added a some last comments but it works nicely!  

also just pushed a small commit at https://github.com/scaffold-eth/scaffold-eth-2/pull/972/commits/c1216fa944613a79f49113959abcc69fe31e7706 to hide private key during account:import (behavior inline with hardhat account:import)

2025-03-03 06:34 UTC, technophile-04 commented on packages/foundry/scripts-js/getAddressBalance.js
Let's remvoe this also remove `chec-balance` from makefile I think we don't need this. 

We have `yarn account` which uses checkAccountBalnce right?

2025-03-03 06:34 UTC, technophile-04 commented on packages/foundry/scripts-js/ListAccount.js
rename this to ListKeystores

2025-03-03 06:34 UTC, technophile-04 commented on packages/foundry/scripts-js/selectKeystore.js
Rename this to SelectOrCreateKeystore?

2025-03-03 09:04 UTC, portdeveloper commented on packages/foundry/Makefile
> +	@node scripts-js/ListAccount.js $(RPC_URL)
Thanks! just updated it to yarn account and also removed RPC_URL from that command as it is not needed

2025-03-03 09:34 UTC, portdeveloper commented on packages/foundry/.env.example
> +LOCALHOST_KEYSTORE_ACCOUNT=scaffold-eth-default
Or:
# Keystore account to be used for localhost deployments only

2025-03-04 06:33 UTC, technophile-04 commented on packages/foundry/.env.example
> +LOCALHOST_KEYSTORE_ACCOUNT=scaffold-eth-default
Yup updated at 76cf9874ae17 also removed the above lines on `DEPLOYER_PRIVATE_KEY `

2025-03-04 08:15 UTC, technophile-04 approved these changes
TYSM Port!! just pushed some commits this is looking solid now 🙌 

Will create a PR to update the SE-2 docs merging this now 🚀🚀

2025-03-04 08:16 UTC, merged